- name: variables from prompt 
  hosts: local 
  connection: local 
  vars_prompt:
  - name: username 
    prompt: what is your username?
    private: false 
  - name: password 
    prompt: what is your password? 
    private: false 
  tasks: 
  - name: Print throgh prompt 
    ansible.builtin.debug: 
     msg: "Hello, The Username is: {{ username }}, Password is: {{ password }}"