- name: play level variables 
  hosts: local 
  connection: local # Ansible is connecting to localhost
  vars: 
    NAME: From play level
  # vars_files:
  # - course.yaml
  tasks: 
  - name: print play level vars 
    # vars: 
    #  NAME: from task level
    ansible.builtin.debug: 
     msg: "Name: {{ NAME }}"